@startuml
title Use Case Diagram for VR Gaming


:GAm3r:
("Meta Quest 2 - VR Headset") as VRH


rectangle "Gaming PC" as PC {
  rectangle "Half-Life Alyx" as HLA
  (Steam)
  ("Occulus Rift App") as ORA

  (Steam) -> HLA : Starts
  (Steam) -> ORA : Starts
}

rectangle "Wi-Fi Router" as WR {
  (LAN)
}

GAm3r -> VRH : Uses
GAm3r -down-> PC : Boots
GAm3r -> Steam : Launches

VRH .. PC : "Optionally: Wired"
ORA <.. HLA : "Leverages Streaming API"
ORA -> WR : "Streams"
WR -> VRH : "Streams"

@enduml
